/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VerifyEmailRouteImport } from './routes/verify-email'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as AccountRouteImport } from './routes/account'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AccountIndexRouteImport } from './routes/account.index'
import { Route as AppIndexRouteImport } from './routes/_app.index'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'
import { Route as AdminPaymentsRouteImport } from './routes/admin.payments'
import { Route as AdminOrdersRouteImport } from './routes/admin.orders'
import { Route as AdminCustomersRouteImport } from './routes/admin.customers'
import { Route as AccountWalletRouteImport } from './routes/account.wallet'
import { Route as AccountSecurityRouteImport } from './routes/account.security'
import { Route as AccountReviewsRouteImport } from './routes/account.reviews'
import { Route as AccountProfileRouteImport } from './routes/account.profile'
import { Route as AccountNotificationsRouteImport } from './routes/account.notifications'
import { Route as AccountFavoritesRouteImport } from './routes/account.favorites'
import { Route as AccountCouponsRouteImport } from './routes/account.coupons'
import { Route as AccountClaimsRouteImport } from './routes/account.claims'
import { Route as AccountAffiliateRouteImport } from './routes/account.affiliate'
import { Route as AccountAddressesRouteImport } from './routes/account.addresses'
import { Route as AccountSplatRouteImport } from './routes/account.$'
import { Route as AppProductsRouteImport } from './routes/_app.products'
import { Route as AppOrdersRouteImport } from './routes/_app.orders'
import { Route as AppCustomizeRouteImport } from './routes/_app.customize'
import { Route as AppCustomersRouteImport } from './routes/_app.customers'
import { Route as AppContactRouteImport } from './routes/_app.contact'
import { Route as AppCompareRouteImport } from './routes/_app.compare'
import { Route as AppCheckoutRouteImport } from './routes/_app.checkout'
import { Route as AppCartRouteImport } from './routes/_app.cart'
import { Route as AppAboutRouteImport } from './routes/_app.about'
import { Route as AppSplatRouteImport } from './routes/_app.$'
import { Route as AdminProductsIndexRouteImport } from './routes/admin.products.index'
import { Route as AccountWalletIndexRouteImport } from './routes/account.wallet.index'
import { Route as AppProductsIndexRouteImport } from './routes/_app.products.index'
import { Route as ApiPublicHealthRouteImport } from './routes/api/public/health'
import { Route as ApiPublicContactRouteImport } from './routes/api/public/contact'
import { Route as ApiPublicC2c2pWebhookRouteImport } from './routes/api/public/c2c2p-webhook'
import { Route as ApiPublicC2c2pStatusRouteImport } from './routes/api/public/c2c2p-status'
import { Route as ApiPublicAuthConfirmSignupRouteImport } from './routes/api/public/auth-confirm-signup'
import { Route as AdminOrdersIdRouteImport } from './routes/admin.orders.$id'
import { Route as AccountWalletTopupRouteImport } from './routes/account.wallet.topup'
import { Route as AccountClaimsNewRouteImport } from './routes/account.claims.new'
import { Route as AccountClaimsIdRouteImport } from './routes/account.claims.$id'
import { Route as AppQuotationIdRouteImport } from './routes/_app.quotation.$id'
import { Route as AppProductsIdRouteImport } from './routes/_app.products.$id'
import { Route as AppOrdersIdRouteImport } from './routes/_app.orders.$id'
import { Route as AppCustomProductIdRouteImport } from './routes/_app.custom.$productId'
import { Route as AppOrdersIdPayRouteImport } from './routes/_app.orders.$id.pay'

const VerifyEmailRoute = VerifyEmailRouteImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountIndexRoute = AccountIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AccountRoute,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPaymentsRoute = AdminPaymentsRouteImport.update({
  id: '/admin/payments',
  path: '/admin/payments',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminOrdersRoute = AdminOrdersRouteImport.update({
  id: '/admin/orders',
  path: '/admin/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCustomersRoute = AdminCustomersRouteImport.update({
  id: '/admin/customers',
  path: '/admin/customers',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountWalletRoute = AccountWalletRouteImport.update({
  id: '/wallet',
  path: '/wallet',
  getParentRoute: () => AccountRoute,
} as any)
const AccountSecurityRoute = AccountSecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => AccountRoute,
} as any)
const AccountReviewsRoute = AccountReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => AccountRoute,
} as any)
const AccountProfileRoute = AccountProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AccountRoute,
} as any)
const AccountNotificationsRoute = AccountNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AccountRoute,
} as any)
const AccountFavoritesRoute = AccountFavoritesRouteImport.update({
  id: '/favorites',
  path: '/favorites',
  getParentRoute: () => AccountRoute,
} as any)
const AccountCouponsRoute = AccountCouponsRouteImport.update({
  id: '/coupons',
  path: '/coupons',
  getParentRoute: () => AccountRoute,
} as any)
const AccountClaimsRoute = AccountClaimsRouteImport.update({
  id: '/claims',
  path: '/claims',
  getParentRoute: () => AccountRoute,
} as any)
const AccountAffiliateRoute = AccountAffiliateRouteImport.update({
  id: '/affiliate',
  path: '/affiliate',
  getParentRoute: () => AccountRoute,
} as any)
const AccountAddressesRoute = AccountAddressesRouteImport.update({
  id: '/addresses',
  path: '/addresses',
  getParentRoute: () => AccountRoute,
} as any)
const AccountSplatRoute = AccountSplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => AccountRoute,
} as any)
const AppProductsRoute = AppProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => AppRoute,
} as any)
const AppOrdersRoute = AppOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => AppRoute,
} as any)
const AppCustomizeRoute = AppCustomizeRouteImport.update({
  id: '/customize',
  path: '/customize',
  getParentRoute: () => AppRoute,
} as any)
const AppCustomersRoute = AppCustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => AppRoute,
} as any)
const AppContactRoute = AppContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => AppRoute,
} as any)
const AppCompareRoute = AppCompareRouteImport.update({
  id: '/compare',
  path: '/compare',
  getParentRoute: () => AppRoute,
} as any)
const AppCheckoutRoute = AppCheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => AppRoute,
} as any)
const AppCartRoute = AppCartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => AppRoute,
} as any)
const AppAboutRoute = AppAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => AppRoute,
} as any)
const AppSplatRoute = AppSplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => AppRoute,
} as any)
const AdminProductsIndexRoute = AdminProductsIndexRouteImport.update({
  id: '/admin/products/',
  path: '/admin/products/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountWalletIndexRoute = AccountWalletIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AccountWalletRoute,
} as any)
const AppProductsIndexRoute = AppProductsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppProductsRoute,
} as any)
const ApiPublicHealthRoute = ApiPublicHealthRouteImport.update({
  id: '/api/public/health',
  path: '/api/public/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicContactRoute = ApiPublicContactRouteImport.update({
  id: '/api/public/contact',
  path: '/api/public/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicC2c2pWebhookRoute = ApiPublicC2c2pWebhookRouteImport.update({
  id: '/api/public/c2c2p-webhook',
  path: '/api/public/c2c2p-webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicC2c2pStatusRoute = ApiPublicC2c2pStatusRouteImport.update({
  id: '/api/public/c2c2p-status',
  path: '/api/public/c2c2p-status',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicAuthConfirmSignupRoute =
  ApiPublicAuthConfirmSignupRouteImport.update({
    id: '/api/public/auth-confirm-signup',
    path: '/api/public/auth-confirm-signup',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdminOrdersIdRoute = AdminOrdersIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AdminOrdersRoute,
} as any)
const AccountWalletTopupRoute = AccountWalletTopupRouteImport.update({
  id: '/topup',
  path: '/topup',
  getParentRoute: () => AccountWalletRoute,
} as any)
const AccountClaimsNewRoute = AccountClaimsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AccountClaimsRoute,
} as any)
const AccountClaimsIdRoute = AccountClaimsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AccountClaimsRoute,
} as any)
const AppQuotationIdRoute = AppQuotationIdRouteImport.update({
  id: '/quotation/$id',
  path: '/quotation/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppProductsIdRoute = AppProductsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppProductsRoute,
} as any)
const AppOrdersIdRoute = AppOrdersIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppOrdersRoute,
} as any)
const AppCustomProductIdRoute = AppCustomProductIdRouteImport.update({
  id: '/custom/$productId',
  path: '/custom/$productId',
  getParentRoute: () => AppRoute,
} as any)
const AppOrdersIdPayRoute = AppOrdersIdPayRouteImport.update({
  id: '/pay',
  path: '/pay',
  getParentRoute: () => AppOrdersIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/account': typeof AccountRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/verify-email': typeof VerifyEmailRoute
  '/$': typeof AppSplatRoute
  '/about': typeof AppAboutRoute
  '/cart': typeof AppCartRoute
  '/checkout': typeof AppCheckoutRoute
  '/compare': typeof AppCompareRoute
  '/contact': typeof AppContactRoute
  '/customers': typeof AppCustomersRoute
  '/customize': typeof AppCustomizeRoute
  '/orders': typeof AppOrdersRouteWithChildren
  '/products': typeof AppProductsRouteWithChildren
  '/account/$': typeof AccountSplatRoute
  '/account/addresses': typeof AccountAddressesRoute
  '/account/affiliate': typeof AccountAffiliateRoute
  '/account/claims': typeof AccountClaimsRouteWithChildren
  '/account/coupons': typeof AccountCouponsRoute
  '/account/favorites': typeof AccountFavoritesRoute
  '/account/notifications': typeof AccountNotificationsRoute
  '/account/profile': typeof AccountProfileRoute
  '/account/reviews': typeof AccountReviewsRoute
  '/account/security': typeof AccountSecurityRoute
  '/account/wallet': typeof AccountWalletRouteWithChildren
  '/admin/customers': typeof AdminCustomersRoute
  '/admin/orders': typeof AdminOrdersRouteWithChildren
  '/admin/payments': typeof AdminPaymentsRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/account/': typeof AccountIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/custom/$productId': typeof AppCustomProductIdRoute
  '/orders/$id': typeof AppOrdersIdRouteWithChildren
  '/products/$id': typeof AppProductsIdRoute
  '/quotation/$id': typeof AppQuotationIdRoute
  '/account/claims/$id': typeof AccountClaimsIdRoute
  '/account/claims/new': typeof AccountClaimsNewRoute
  '/account/wallet/topup': typeof AccountWalletTopupRoute
  '/admin/orders/$id': typeof AdminOrdersIdRoute
  '/api/public/auth-confirm-signup': typeof ApiPublicAuthConfirmSignupRoute
  '/api/public/c2c2p-status': typeof ApiPublicC2c2pStatusRoute
  '/api/public/c2c2p-webhook': typeof ApiPublicC2c2pWebhookRoute
  '/api/public/contact': typeof ApiPublicContactRoute
  '/api/public/health': typeof ApiPublicHealthRoute
  '/products/': typeof AppProductsIndexRoute
  '/account/wallet/': typeof AccountWalletIndexRoute
  '/admin/products/': typeof AdminProductsIndexRoute
  '/orders/$id/pay': typeof AppOrdersIdPayRoute
}
export interface FileRoutesByTo {
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/verify-email': typeof VerifyEmailRoute
  '/$': typeof AppSplatRoute
  '/about': typeof AppAboutRoute
  '/cart': typeof AppCartRoute
  '/checkout': typeof AppCheckoutRoute
  '/compare': typeof AppCompareRoute
  '/contact': typeof AppContactRoute
  '/customers': typeof AppCustomersRoute
  '/customize': typeof AppCustomizeRoute
  '/orders': typeof AppOrdersRouteWithChildren
  '/account/$': typeof AccountSplatRoute
  '/account/addresses': typeof AccountAddressesRoute
  '/account/affiliate': typeof AccountAffiliateRoute
  '/account/claims': typeof AccountClaimsRouteWithChildren
  '/account/coupons': typeof AccountCouponsRoute
  '/account/favorites': typeof AccountFavoritesRoute
  '/account/notifications': typeof AccountNotificationsRoute
  '/account/profile': typeof AccountProfileRoute
  '/account/reviews': typeof AccountReviewsRoute
  '/account/security': typeof AccountSecurityRoute
  '/admin/customers': typeof AdminCustomersRoute
  '/admin/orders': typeof AdminOrdersRouteWithChildren
  '/admin/payments': typeof AdminPaymentsRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/': typeof AppIndexRoute
  '/account': typeof AccountIndexRoute
  '/admin': typeof AdminIndexRoute
  '/custom/$productId': typeof AppCustomProductIdRoute
  '/orders/$id': typeof AppOrdersIdRouteWithChildren
  '/products/$id': typeof AppProductsIdRoute
  '/quotation/$id': typeof AppQuotationIdRoute
  '/account/claims/$id': typeof AccountClaimsIdRoute
  '/account/claims/new': typeof AccountClaimsNewRoute
  '/account/wallet/topup': typeof AccountWalletTopupRoute
  '/admin/orders/$id': typeof AdminOrdersIdRoute
  '/api/public/auth-confirm-signup': typeof ApiPublicAuthConfirmSignupRoute
  '/api/public/c2c2p-status': typeof ApiPublicC2c2pStatusRoute
  '/api/public/c2c2p-webhook': typeof ApiPublicC2c2pWebhookRoute
  '/api/public/contact': typeof ApiPublicContactRoute
  '/api/public/health': typeof ApiPublicHealthRoute
  '/products': typeof AppProductsIndexRoute
  '/account/wallet': typeof AccountWalletIndexRoute
  '/admin/products': typeof AdminProductsIndexRoute
  '/orders/$id/pay': typeof AppOrdersIdPayRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/account': typeof AccountRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/verify-email': typeof VerifyEmailRoute
  '/_app/$': typeof AppSplatRoute
  '/_app/about': typeof AppAboutRoute
  '/_app/cart': typeof AppCartRoute
  '/_app/checkout': typeof AppCheckoutRoute
  '/_app/compare': typeof AppCompareRoute
  '/_app/contact': typeof AppContactRoute
  '/_app/customers': typeof AppCustomersRoute
  '/_app/customize': typeof AppCustomizeRoute
  '/_app/orders': typeof AppOrdersRouteWithChildren
  '/_app/products': typeof AppProductsRouteWithChildren
  '/account/$': typeof AccountSplatRoute
  '/account/addresses': typeof AccountAddressesRoute
  '/account/affiliate': typeof AccountAffiliateRoute
  '/account/claims': typeof AccountClaimsRouteWithChildren
  '/account/coupons': typeof AccountCouponsRoute
  '/account/favorites': typeof AccountFavoritesRoute
  '/account/notifications': typeof AccountNotificationsRoute
  '/account/profile': typeof AccountProfileRoute
  '/account/reviews': typeof AccountReviewsRoute
  '/account/security': typeof AccountSecurityRoute
  '/account/wallet': typeof AccountWalletRouteWithChildren
  '/admin/customers': typeof AdminCustomersRoute
  '/admin/orders': typeof AdminOrdersRouteWithChildren
  '/admin/payments': typeof AdminPaymentsRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/_app/': typeof AppIndexRoute
  '/account/': typeof AccountIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/_app/custom/$productId': typeof AppCustomProductIdRoute
  '/_app/orders/$id': typeof AppOrdersIdRouteWithChildren
  '/_app/products/$id': typeof AppProductsIdRoute
  '/_app/quotation/$id': typeof AppQuotationIdRoute
  '/account/claims/$id': typeof AccountClaimsIdRoute
  '/account/claims/new': typeof AccountClaimsNewRoute
  '/account/wallet/topup': typeof AccountWalletTopupRoute
  '/admin/orders/$id': typeof AdminOrdersIdRoute
  '/api/public/auth-confirm-signup': typeof ApiPublicAuthConfirmSignupRoute
  '/api/public/c2c2p-status': typeof ApiPublicC2c2pStatusRoute
  '/api/public/c2c2p-webhook': typeof ApiPublicC2c2pWebhookRoute
  '/api/public/contact': typeof ApiPublicContactRoute
  '/api/public/health': typeof ApiPublicHealthRoute
  '/_app/products/': typeof AppProductsIndexRoute
  '/account/wallet/': typeof AccountWalletIndexRoute
  '/admin/products/': typeof AdminProductsIndexRoute
  '/_app/orders/$id/pay': typeof AppOrdersIdPayRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/sitemap.xml'
    | '/verify-email'
    | '/$'
    | '/about'
    | '/cart'
    | '/checkout'
    | '/compare'
    | '/contact'
    | '/customers'
    | '/customize'
    | '/orders'
    | '/products'
    | '/account/$'
    | '/account/addresses'
    | '/account/affiliate'
    | '/account/claims'
    | '/account/coupons'
    | '/account/favorites'
    | '/account/notifications'
    | '/account/profile'
    | '/account/reviews'
    | '/account/security'
    | '/account/wallet'
    | '/admin/customers'
    | '/admin/orders'
    | '/admin/payments'
    | '/auth/callback'
    | '/account/'
    | '/admin/'
    | '/custom/$productId'
    | '/orders/$id'
    | '/products/$id'
    | '/quotation/$id'
    | '/account/claims/$id'
    | '/account/claims/new'
    | '/account/wallet/topup'
    | '/admin/orders/$id'
    | '/api/public/auth-confirm-signup'
    | '/api/public/c2c2p-status'
    | '/api/public/c2c2p-webhook'
    | '/api/public/contact'
    | '/api/public/health'
    | '/products/'
    | '/account/wallet/'
    | '/admin/products/'
    | '/orders/$id/pay'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/sitemap.xml'
    | '/verify-email'
    | '/$'
    | '/about'
    | '/cart'
    | '/checkout'
    | '/compare'
    | '/contact'
    | '/customers'
    | '/customize'
    | '/orders'
    | '/account/$'
    | '/account/addresses'
    | '/account/affiliate'
    | '/account/claims'
    | '/account/coupons'
    | '/account/favorites'
    | '/account/notifications'
    | '/account/profile'
    | '/account/reviews'
    | '/account/security'
    | '/admin/customers'
    | '/admin/orders'
    | '/admin/payments'
    | '/auth/callback'
    | '/'
    | '/account'
    | '/admin'
    | '/custom/$productId'
    | '/orders/$id'
    | '/products/$id'
    | '/quotation/$id'
    | '/account/claims/$id'
    | '/account/claims/new'
    | '/account/wallet/topup'
    | '/admin/orders/$id'
    | '/api/public/auth-confirm-signup'
    | '/api/public/c2c2p-status'
    | '/api/public/c2c2p-webhook'
    | '/api/public/contact'
    | '/api/public/health'
    | '/products'
    | '/account/wallet'
    | '/admin/products'
    | '/orders/$id/pay'
  id:
    | '__root__'
    | '/_app'
    | '/account'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/sitemap.xml'
    | '/verify-email'
    | '/_app/$'
    | '/_app/about'
    | '/_app/cart'
    | '/_app/checkout'
    | '/_app/compare'
    | '/_app/contact'
    | '/_app/customers'
    | '/_app/customize'
    | '/_app/orders'
    | '/_app/products'
    | '/account/$'
    | '/account/addresses'
    | '/account/affiliate'
    | '/account/claims'
    | '/account/coupons'
    | '/account/favorites'
    | '/account/notifications'
    | '/account/profile'
    | '/account/reviews'
    | '/account/security'
    | '/account/wallet'
    | '/admin/customers'
    | '/admin/orders'
    | '/admin/payments'
    | '/auth/callback'
    | '/_app/'
    | '/account/'
    | '/admin/'
    | '/_app/custom/$productId'
    | '/_app/orders/$id'
    | '/_app/products/$id'
    | '/_app/quotation/$id'
    | '/account/claims/$id'
    | '/account/claims/new'
    | '/account/wallet/topup'
    | '/admin/orders/$id'
    | '/api/public/auth-confirm-signup'
    | '/api/public/c2c2p-status'
    | '/api/public/c2c2p-webhook'
    | '/api/public/contact'
    | '/api/public/health'
    | '/_app/products/'
    | '/account/wallet/'
    | '/admin/products/'
    | '/_app/orders/$id/pay'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  AccountRoute: typeof AccountRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  VerifyEmailRoute: typeof VerifyEmailRoute
  AdminCustomersRoute: typeof AdminCustomersRoute
  AdminOrdersRoute: typeof AdminOrdersRouteWithChildren
  AdminPaymentsRoute: typeof AdminPaymentsRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  AdminIndexRoute: typeof AdminIndexRoute
  ApiPublicAuthConfirmSignupRoute: typeof ApiPublicAuthConfirmSignupRoute
  ApiPublicC2c2pStatusRoute: typeof ApiPublicC2c2pStatusRoute
  ApiPublicC2c2pWebhookRoute: typeof ApiPublicC2c2pWebhookRoute
  ApiPublicContactRoute: typeof ApiPublicContactRoute
  ApiPublicHealthRoute: typeof ApiPublicHealthRoute
  AdminProductsIndexRoute: typeof AdminProductsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/verify-email': {
      id: '/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof VerifyEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/': {
      id: '/account/'
      path: '/'
      fullPath: '/account/'
      preLoaderRoute: typeof AccountIndexRouteImport
      parentRoute: typeof AccountRoute
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/payments': {
      id: '/admin/payments'
      path: '/admin/payments'
      fullPath: '/admin/payments'
      preLoaderRoute: typeof AdminPaymentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/orders': {
      id: '/admin/orders'
      path: '/admin/orders'
      fullPath: '/admin/orders'
      preLoaderRoute: typeof AdminOrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/customers': {
      id: '/admin/customers'
      path: '/admin/customers'
      fullPath: '/admin/customers'
      preLoaderRoute: typeof AdminCustomersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/wallet': {
      id: '/account/wallet'
      path: '/wallet'
      fullPath: '/account/wallet'
      preLoaderRoute: typeof AccountWalletRouteImport
      parentRoute: typeof AccountRoute
    }
    '/account/security': {
      id: '/account/security'
      path: '/security'
      fullPath: '/account/security'
      preLoaderRoute: typeof AccountSecurityRouteImport
      parentRoute: typeof AccountRoute
    }
    '/account/reviews': {
      id: '/account/reviews'
      path: '/reviews'
      fullPath: '/account/reviews'
      preLoaderRoute: typeof AccountReviewsRouteImport
      parentRoute: typeof AccountRoute
    }
    '/account/profile': {
      id: '/account/profile'
      path: '/profile'
      fullPath: '/account/profile'
      preLoaderRoute: typeof AccountProfileRouteImport
      parentRoute: typeof AccountRoute
    }
    '/account/notifications': {
      id: '/account/notifications'
      path: '/notifications'
      fullPath: '/account/notifications'
      preLoaderRoute: typeof AccountNotificationsRouteImport
      parentRoute: typeof AccountRoute
    }
    '/account/favorites': {
      id: '/account/favorites'
      path: '/favorites'
      fullPath: '/account/favorites'
      preLoaderRoute: typeof AccountFavoritesRouteImport
      parentRoute: typeof AccountRoute
    }
    '/account/coupons': {
      id: '/account/coupons'
      path: '/coupons'
      fullPath: '/account/coupons'
      preLoaderRoute: typeof AccountCouponsRouteImport
      parentRoute: typeof AccountRoute
    }
    '/account/claims': {
      id: '/account/claims'
      path: '/claims'
      fullPath: '/account/claims'
      preLoaderRoute: typeof AccountClaimsRouteImport
      parentRoute: typeof AccountRoute
    }
    '/account/affiliate': {
      id: '/account/affiliate'
      path: '/affiliate'
      fullPath: '/account/affiliate'
      preLoaderRoute: typeof AccountAffiliateRouteImport
      parentRoute: typeof AccountRoute
    }
    '/account/addresses': {
      id: '/account/addresses'
      path: '/addresses'
      fullPath: '/account/addresses'
      preLoaderRoute: typeof AccountAddressesRouteImport
      parentRoute: typeof AccountRoute
    }
    '/account/$': {
      id: '/account/$'
      path: '/$'
      fullPath: '/account/$'
      preLoaderRoute: typeof AccountSplatRouteImport
      parentRoute: typeof AccountRoute
    }
    '/_app/products': {
      id: '/_app/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof AppProductsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/orders': {
      id: '/_app/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof AppOrdersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/customize': {
      id: '/_app/customize'
      path: '/customize'
      fullPath: '/customize'
      preLoaderRoute: typeof AppCustomizeRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/customers': {
      id: '/_app/customers'
      path: '/customers'
      fullPath: '/customers'
      preLoaderRoute: typeof AppCustomersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/contact': {
      id: '/_app/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof AppContactRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/compare': {
      id: '/_app/compare'
      path: '/compare'
      fullPath: '/compare'
      preLoaderRoute: typeof AppCompareRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/checkout': {
      id: '/_app/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof AppCheckoutRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/cart': {
      id: '/_app/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof AppCartRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/about': {
      id: '/_app/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AppAboutRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/$': {
      id: '/_app/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof AppSplatRouteImport
      parentRoute: typeof AppRoute
    }
    '/admin/products/': {
      id: '/admin/products/'
      path: '/admin/products'
      fullPath: '/admin/products/'
      preLoaderRoute: typeof AdminProductsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/wallet/': {
      id: '/account/wallet/'
      path: '/'
      fullPath: '/account/wallet/'
      preLoaderRoute: typeof AccountWalletIndexRouteImport
      parentRoute: typeof AccountWalletRoute
    }
    '/_app/products/': {
      id: '/_app/products/'
      path: '/'
      fullPath: '/products/'
      preLoaderRoute: typeof AppProductsIndexRouteImport
      parentRoute: typeof AppProductsRoute
    }
    '/api/public/health': {
      id: '/api/public/health'
      path: '/api/public/health'
      fullPath: '/api/public/health'
      preLoaderRoute: typeof ApiPublicHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/contact': {
      id: '/api/public/contact'
      path: '/api/public/contact'
      fullPath: '/api/public/contact'
      preLoaderRoute: typeof ApiPublicContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/c2c2p-webhook': {
      id: '/api/public/c2c2p-webhook'
      path: '/api/public/c2c2p-webhook'
      fullPath: '/api/public/c2c2p-webhook'
      preLoaderRoute: typeof ApiPublicC2c2pWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/c2c2p-status': {
      id: '/api/public/c2c2p-status'
      path: '/api/public/c2c2p-status'
      fullPath: '/api/public/c2c2p-status'
      preLoaderRoute: typeof ApiPublicC2c2pStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/auth-confirm-signup': {
      id: '/api/public/auth-confirm-signup'
      path: '/api/public/auth-confirm-signup'
      fullPath: '/api/public/auth-confirm-signup'
      preLoaderRoute: typeof ApiPublicAuthConfirmSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/orders/$id': {
      id: '/admin/orders/$id'
      path: '/$id'
      fullPath: '/admin/orders/$id'
      preLoaderRoute: typeof AdminOrdersIdRouteImport
      parentRoute: typeof AdminOrdersRoute
    }
    '/account/wallet/topup': {
      id: '/account/wallet/topup'
      path: '/topup'
      fullPath: '/account/wallet/topup'
      preLoaderRoute: typeof AccountWalletTopupRouteImport
      parentRoute: typeof AccountWalletRoute
    }
    '/account/claims/new': {
      id: '/account/claims/new'
      path: '/new'
      fullPath: '/account/claims/new'
      preLoaderRoute: typeof AccountClaimsNewRouteImport
      parentRoute: typeof AccountClaimsRoute
    }
    '/account/claims/$id': {
      id: '/account/claims/$id'
      path: '/$id'
      fullPath: '/account/claims/$id'
      preLoaderRoute: typeof AccountClaimsIdRouteImport
      parentRoute: typeof AccountClaimsRoute
    }
    '/_app/quotation/$id': {
      id: '/_app/quotation/$id'
      path: '/quotation/$id'
      fullPath: '/quotation/$id'
      preLoaderRoute: typeof AppQuotationIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/products/$id': {
      id: '/_app/products/$id'
      path: '/$id'
      fullPath: '/products/$id'
      preLoaderRoute: typeof AppProductsIdRouteImport
      parentRoute: typeof AppProductsRoute
    }
    '/_app/orders/$id': {
      id: '/_app/orders/$id'
      path: '/$id'
      fullPath: '/orders/$id'
      preLoaderRoute: typeof AppOrdersIdRouteImport
      parentRoute: typeof AppOrdersRoute
    }
    '/_app/custom/$productId': {
      id: '/_app/custom/$productId'
      path: '/custom/$productId'
      fullPath: '/custom/$productId'
      preLoaderRoute: typeof AppCustomProductIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/orders/$id/pay': {
      id: '/_app/orders/$id/pay'
      path: '/pay'
      fullPath: '/orders/$id/pay'
      preLoaderRoute: typeof AppOrdersIdPayRouteImport
      parentRoute: typeof AppOrdersIdRoute
    }
  }
}

interface AppOrdersIdRouteChildren {
  AppOrdersIdPayRoute: typeof AppOrdersIdPayRoute
}

const AppOrdersIdRouteChildren: AppOrdersIdRouteChildren = {
  AppOrdersIdPayRoute: AppOrdersIdPayRoute,
}

const AppOrdersIdRouteWithChildren = AppOrdersIdRoute._addFileChildren(
  AppOrdersIdRouteChildren,
)

interface AppOrdersRouteChildren {
  AppOrdersIdRoute: typeof AppOrdersIdRouteWithChildren
}

const AppOrdersRouteChildren: AppOrdersRouteChildren = {
  AppOrdersIdRoute: AppOrdersIdRouteWithChildren,
}

const AppOrdersRouteWithChildren = AppOrdersRoute._addFileChildren(
  AppOrdersRouteChildren,
)

interface AppProductsRouteChildren {
  AppProductsIdRoute: typeof AppProductsIdRoute
  AppProductsIndexRoute: typeof AppProductsIndexRoute
}

const AppProductsRouteChildren: AppProductsRouteChildren = {
  AppProductsIdRoute: AppProductsIdRoute,
  AppProductsIndexRoute: AppProductsIndexRoute,
}

const AppProductsRouteWithChildren = AppProductsRoute._addFileChildren(
  AppProductsRouteChildren,
)

interface AppRouteChildren {
  AppSplatRoute: typeof AppSplatRoute
  AppAboutRoute: typeof AppAboutRoute
  AppCartRoute: typeof AppCartRoute
  AppCheckoutRoute: typeof AppCheckoutRoute
  AppCompareRoute: typeof AppCompareRoute
  AppContactRoute: typeof AppContactRoute
  AppCustomersRoute: typeof AppCustomersRoute
  AppCustomizeRoute: typeof AppCustomizeRoute
  AppOrdersRoute: typeof AppOrdersRouteWithChildren
  AppProductsRoute: typeof AppProductsRouteWithChildren
  AppIndexRoute: typeof AppIndexRoute
  AppCustomProductIdRoute: typeof AppCustomProductIdRoute
  AppQuotationIdRoute: typeof AppQuotationIdRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppSplatRoute: AppSplatRoute,
  AppAboutRoute: AppAboutRoute,
  AppCartRoute: AppCartRoute,
  AppCheckoutRoute: AppCheckoutRoute,
  AppCompareRoute: AppCompareRoute,
  AppContactRoute: AppContactRoute,
  AppCustomersRoute: AppCustomersRoute,
  AppCustomizeRoute: AppCustomizeRoute,
  AppOrdersRoute: AppOrdersRouteWithChildren,
  AppProductsRoute: AppProductsRouteWithChildren,
  AppIndexRoute: AppIndexRoute,
  AppCustomProductIdRoute: AppCustomProductIdRoute,
  AppQuotationIdRoute: AppQuotationIdRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface AccountClaimsRouteChildren {
  AccountClaimsIdRoute: typeof AccountClaimsIdRoute
  AccountClaimsNewRoute: typeof AccountClaimsNewRoute
}

const AccountClaimsRouteChildren: AccountClaimsRouteChildren = {
  AccountClaimsIdRoute: AccountClaimsIdRoute,
  AccountClaimsNewRoute: AccountClaimsNewRoute,
}

const AccountClaimsRouteWithChildren = AccountClaimsRoute._addFileChildren(
  AccountClaimsRouteChildren,
)

interface AccountWalletRouteChildren {
  AccountWalletTopupRoute: typeof AccountWalletTopupRoute
  AccountWalletIndexRoute: typeof AccountWalletIndexRoute
}

const AccountWalletRouteChildren: AccountWalletRouteChildren = {
  AccountWalletTopupRoute: AccountWalletTopupRoute,
  AccountWalletIndexRoute: AccountWalletIndexRoute,
}

const AccountWalletRouteWithChildren = AccountWalletRoute._addFileChildren(
  AccountWalletRouteChildren,
)

interface AccountRouteChildren {
  AccountSplatRoute: typeof AccountSplatRoute
  AccountAddressesRoute: typeof AccountAddressesRoute
  AccountAffiliateRoute: typeof AccountAffiliateRoute
  AccountClaimsRoute: typeof AccountClaimsRouteWithChildren
  AccountCouponsRoute: typeof AccountCouponsRoute
  AccountFavoritesRoute: typeof AccountFavoritesRoute
  AccountNotificationsRoute: typeof AccountNotificationsRoute
  AccountProfileRoute: typeof AccountProfileRoute
  AccountReviewsRoute: typeof AccountReviewsRoute
  AccountSecurityRoute: typeof AccountSecurityRoute
  AccountWalletRoute: typeof AccountWalletRouteWithChildren
  AccountIndexRoute: typeof AccountIndexRoute
}

const AccountRouteChildren: AccountRouteChildren = {
  AccountSplatRoute: AccountSplatRoute,
  AccountAddressesRoute: AccountAddressesRoute,
  AccountAffiliateRoute: AccountAffiliateRoute,
  AccountClaimsRoute: AccountClaimsRouteWithChildren,
  AccountCouponsRoute: AccountCouponsRoute,
  AccountFavoritesRoute: AccountFavoritesRoute,
  AccountNotificationsRoute: AccountNotificationsRoute,
  AccountProfileRoute: AccountProfileRoute,
  AccountReviewsRoute: AccountReviewsRoute,
  AccountSecurityRoute: AccountSecurityRoute,
  AccountWalletRoute: AccountWalletRouteWithChildren,
  AccountIndexRoute: AccountIndexRoute,
}

const AccountRouteWithChildren =
  AccountRoute._addFileChildren(AccountRouteChildren)

interface AdminOrdersRouteChildren {
  AdminOrdersIdRoute: typeof AdminOrdersIdRoute
}

const AdminOrdersRouteChildren: AdminOrdersRouteChildren = {
  AdminOrdersIdRoute: AdminOrdersIdRoute,
}

const AdminOrdersRouteWithChildren = AdminOrdersRoute._addFileChildren(
  AdminOrdersRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  AccountRoute: AccountRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  VerifyEmailRoute: VerifyEmailRoute,
  AdminCustomersRoute: AdminCustomersRoute,
  AdminOrdersRoute: AdminOrdersRouteWithChildren,
  AdminPaymentsRoute: AdminPaymentsRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  AdminIndexRoute: AdminIndexRoute,
  ApiPublicAuthConfirmSignupRoute: ApiPublicAuthConfirmSignupRoute,
  ApiPublicC2c2pStatusRoute: ApiPublicC2c2pStatusRoute,
  ApiPublicC2c2pWebhookRoute: ApiPublicC2c2pWebhookRoute,
  ApiPublicContactRoute: ApiPublicContactRoute,
  ApiPublicHealthRoute: ApiPublicHealthRoute,
  AdminProductsIndexRoute: AdminProductsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
